# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6605179298989976bfbf11a21e7fb7e8d02f9766108179d13e035a353fb16fafc06677ad126a88bb9ad23d490acd2ed263ec979d12fd065c44543d7a42848084

test:
  secret_key_base: 285400a87e973471a7681b9b939596a6d38e6e7bd6d78ee4a9490f5bb0e2ffa4977d9a7836012fc7e7be23b0eae766a074dd42d3d85a6bc2e58457a580f237dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
