# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc2f7969d641a95d6dd2fb045952159deb48ab84250ca5e146eedd1daf77d85fe4b00aef69ab17406cdf0dcdc0cbedf9f5d839badcad7527f5aba3d41067cfb

test:
  secret_key_base: f5b39a653153a24b02394b3d85a486eee5c5b0b6e53f7e2f018a5441f1f48387bcf2f8c68a03144dad0c3c2b95d0f1d69fb60d337c559c6b4726ed691c7c56ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
