# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ab5e3db02bfe41af63846e7e2f103c55c6efda412090bcaaa9038460e1ff9093aefcce2032c07ee0ad612ae396b0d048411aabe883b6c2a8fa88cfff2270ed

test:
  secret_key_base: db80f5a3ab31674bfd167e78f30011d45b4154e41c14c8b29d01360ed6e3104aaf22f003b015193c6b293ff1ec3d15a336e3914df267a822ba4af4b985678d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
